/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/
class Q2 {

	public static void main(String[] args) {
		 int num1 = 0, num2 = 1; 
		  
	        int counter = 0; 
	  
	        int num3=0;
	        int sum=0;
	        while ((num1<4000000)&&(num2<4000000)) { 
	         num3 = num2 + num1; 
	           
	            if(num3%2==0)
	            {
	            	sum=sum+num3;
	            }
	            if(num3>4000000)
	            {
	            	break;
	            }
	           
	            num1 = num2; 
	            num2 = num3; 
	           

	}
	        System.out.println(sum);

}
}
//output
//4613732
